spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  security:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration